export const types={
    CREATE_USER:"CREATE_USER",
    LOAD_USER:"LOAD_USER",

    LOAD_FLIGHTS:"LOAD_FLIGHTS",
    UPDATE_FLIGHT:"UPDATE_FLIGHT",
    
    LOAD_PASSENGERS:"LOAD_PASSENGERS",
    LOAD_PASSENGERS_BY_FLIGHT:"LOAD_PASSENGERS_BY_FLIGHT",
    UPDATE_PASSENGER:"UPDATE_PASSENGER",
    ADD_PASSENGER:"ADD_PASSENGER",
    CLEAR_STATE:"CLEAR_STATE"
} 